### ISSUE TITLE
InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid rank for input: input Got: 3 Expected: 2 Please fix either the inputs or the model.

### ISSUE THREAD

**Issue by lonngxiang** [dengcunqin/noise-reduction#1]
outputs = ort_session.run(None, {input_name: input_data})；把input_data维度降维了还是报错，麻烦问下这边音频除了变成16000还需要其他处理吗
![image](https://github.com/dengcunqin/noise-reduction/assets/40717349/768a870e-237e-4d71-967a-cc9f96400f83)

**Comment by dengcunqin** [comment]
单声道，采样率16000
